# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aefdc2a63bccd846126efe2c884c59dea3376f6967cd5ea303a05347f88c862983ee4441e02806c5c5a2d59671fb41f84a01a8541c57e30980587b6bbaaf9365

test:
  secret_key_base: d336125d62f7f281fa1365010534daa3ed985a0eff0a91f7c1dc758753e047b5afcd5cebc5feb7f4535e99affc43d676f63b2e3bb7bf51ba151a142004efd4b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
